image:
  - Visual Studio 2017

platform:
  - x86
  - x64

environment:
  matrix:
    - nodejs_version: LTS
    - nodejs_version: Current

install:
  - ps: Install-Product node $env:nodejs_version
  - node --version
  - npm --version
  - npm install
  - npm audit
  - npm run compile

build: off

test_script:
  - npm test --silent

on_failure:
  - type .\out\test\testlogs.txt
