image:
  - Visual Studio 2017

platform:
  - x86
  - x64

environment:
  nodejs_version: "10"

install:
  - ps: Install-Product node $env:nodejs_version
  - node --version
  - npm --version
  - npm install
  - npm audit
  - npm run compile

build: off

test_script:
  - npm test --silent

on_failure:
  - dir .\out\test
  - type .\out\test\FailedTestLogs\log_*.txt
