sudo: false

env:
  global:
    - secure: GnwXBT/tIhfb7dCu2fYOjWxGJ9t9T16Oc36w+vgAPKJ43boDO3xWWUuqb6CL9yQpzH1ZO8M5+twwCt12B0RTeAqIfqKzfFq5V3v9/4DhXi8huUNB3Acv79GbFNSReXyfz+KXth7fA4zO35Rru+/reSXnJZDCrb7bMMN30z5Whe8CnqlINbHocI2UEcb+cjx6J8EGNzzR9OBZbpNdy2kGmq/5buzomZorneiNrI6ap6fZg97ljuwh4VATOqBBhkGWLYOlBVBVWs1Nc7JwwYrEloMp1mB3LxGtn1Ut1zjDPDX4SLOYujAcsuzWcOp0DAwtPi1oc4atnPmCNfPFCtYzCt4hXwSswQkYkJ0jD9jjZomkOSxbq47zTULisj1chGrZiMwJ295cZ7vjnh8FvN5e7KNd4AczUIMIxf0mYGAQYqCajMTTp3S4AzdVd6mXj8x0CJ1p0y1cFHCsK2BLuGbAANfR7oQNfTsChBMhi2uKxgVt0V+ndZ4y+JMTxBkvPoUrdm5ghkTvYdk4mEKDnvxAPmqsstJRaCBBnLNZtkLfrvQW4WB3Z9N0DnnV1z1j6DnceM4GkYOZekOjM8jm5ea/bpLlYm43vW8M5073nM3IfgS+DkZeysSnn0QTvUx96PPSlWCXypo1GVsbKyyKoGkFGhT7Y6FOKJqeMR3M2WHa928=
    - secure: K3woraK3efvVQXzn5xtOfAsimcbrXD1HzSNzDQX6gDZazvRN+vhQqNAD6fFg0JA4cSo7+BzQi2rIRqcDxaPjeWflgbhGhyFBc21xxOchIDVBGXhWhdbHuZ+KS7Qn4xQyzJPr6qRHIcPwlJW8c40q/AXqPkhiVgWJZNYNlpuCNNM+xqyM+FKz2jPmHt0mcyv6vcXMP0eeORu5UC2txMIY2Kcpf9xm486tUStB31mzb4zZzOHjYtr3iAkmp8DiypPWepTKm2Eg8dYiAhqaLqQtZjx5HayBGhAD0HQyuiMiHmzqkCJU0xTvSf+Ky3xOMGtb9WboTIotGeh6+8lIZMRrUQn1bFHF0rQ/Ge4aU9KhAmugd1ycppslU7BtHpasa9vgWV9CqGpIg8F8fihOE0ygEaOAwU41hoI9LisH5YHKNqtBOrfM6Pdm+urQC2hL5wA64nOxLTRZZkaDpFWdXN+etaiJ9bmlMrM8qTZ7dz+Rfrpora9DvuMSmm+RX+ETIb1tqtSS3tO7SVhufnqefRoRwBA8EBmhTRnmWyRVqhwQaqeYzVPWTi6s5Rt2uz3d/7h0NdTpEb2YHcd7V3TC9k+c2nALDFPP1LgFP6AScPVoAYmoDSovOwaxfO9LHPgNzikf50Sz5/zeSariib4iYKSFt/waJ6NU2FIvvP8qVlYO568=
    
language: node_js

node_js:
  - "8"
  - "11"

os:
  - osx
  - linux

before_install:
  - if [ $TRAVIS_OS_NAME == "linux" ]; then
      export CXX="g++-4.9" CC="gcc-4.9" DISPLAY=:99.0;
      sh -e /etc/init.d/xvfb start;
      sleep 3;
    fi

install:
  - npm install
  - npm run compile

script: 
  - npm test --silent

before_deploy:
  - npm install 
  - npm run compile

deploy:
  provider: script
  script: node ./out/repo_scripts/deploy.js
  on:
    condition: "$TRAVIS_OS_NAME = osx"
    node_js: "8"
    repo: matepek/vscode-catch2-test-adapter
    branch: master
    tags: false
