sudo: false

env:
  global:
    - C2_SENTRY_DISABLE=true
    - secure: "wbBkk3ujOixgrplG1baLP6lgjFr6bw2eiOsNYAyfwU8SeSoc4qgp8bGttigHOTwnPfAreLMlnGkFdPF3f8v31AHj98mevHKNxvkeFiRjDc9bI3rEviFnbZMWbsw7svzTw3/D4K1xZuHc46IReOU8OJUaQaAP/VquZ8S0ZLDyUslBLZyhQNgVtp5VmOyHie/iI+KvkOVZfhun2wVa5LJgmJJPCFIcPGdlWTf77InxZohBM1rPBB16UE/gXkLUlrMjqnZWRem92cN+mqkU7xolzeeWKdzvbD6pD0swCS3xbiFfwy9pHgxfDDYdqbQIuFKoRIOeIcSuFm8LQv5kXvdRGLM/aiND34V5rETB+uK9HCh66uDY/lpTVTpY8DlddbTitpgq1on1LEeVPdgvA1MU3wkQD++lrDT4hdNTNCsUvdbocceSlqEmrKycRUJCI8Z9HTnkCTXCITNFEw0brYTgrHE2+KY7ul4CYc0Xu0dHmm6SBHvdU38HLi4MRR/78VVP9anrH1zVVKiLP95vdFrwrXBFGewYVVwv4QjFuwnQFDTCLEYUNctyOF3H8pTLLbY0DWMM1LVU6abHfb0tDYpRCffKJv4Wf9wOcTNCemtaGaxgOY6vcy1/SmpVHa9WQkfDMywZrolByEwflw0wP/yUVdDVfRt/JeAVh9m4EhiHTc4="
    - secure: "KwwThYC5XnQXlt0r3mUfV91N9+4CujoCzrfb9eBhvfTQL0yRofx75saXWhh/HNC8fYsf/3cPV3iASKlUXCw2MjYw7w7pzmbeeszBRkMJQHdDFqaTmDY167vv88Mddd90quanM8EEdCpjvrLLzgGpxQGQzVRZ7z0SmxJIEF/I58aAmC8hZ++5V/zAlwnhCbvs8ppJB7zTf3Ug4rSVr1/q52CK5f0ZVwX1TqOlzHv7KFO7IZV5DWmYHsClvcJbraAtBUa0otNTzr6dIHq8K22MWBULHCvp2JziZ06F3jjfPk7yB0K8Ia8gy73n+rXyW8aikBpCCdhmAjHOOpB5VBM5I2/O1XYJY0rS4v6OoYUcw9rnbGY4tYh/k0We0cKgatbz43k6gYqO9bkjZMqZk/jqieQ8JKwfRQxd2SEd6tViuIzB1p3KqNDcG+0xAjgAMBy6LR8RSDbZJcPJ8Jv1WIB3xxL3m8REzIW3Fm1/hlJ+J1WzebK6D7Ypf0BOrRIU/XObDlpoFf2qdI9RgC/U4EULwUmGqEMd8W3moeU49QHx9MzIz4CEo03OODlP+dgDLmlVsjgP8+/ONUGJC/uqd8TvsNres5IS+/N8V2deLNxyyNvMV1DvbH1ogYnViM51Kn+Jq3bXqj39lYWYVkDk8SE9LR4/gmxwhmDQzuN+uwXi47o="
    - secure: "euDckCIzfWbvdH8YoSm9OMOt7bnEmeWqV9YApz/quRpqe+6RIvKYnFqhC0IpzJaS734sDroJA/ouDITExY8+uEDMg4mnHGHVVfYZSgVjo6tOcVHfWtE2OBLIJ//8DMs1092Q4HAKsKb0iJYDS3Wvk3noaaPHG/sM+Cdo4dsc1ITLcwsLdayrzoO0Mh0AVd1OcVWI8pigm8+io5nPuczje9YrsHVCwYx78jomdWQ8YjMYD+dPsv1qWz3hEpcqXkw3f++nPsNmO6N3dCsaL3zacAFv8BlXVJ/uDmDINlTghJpU4LVt8p21oSi6L9Hcg2SP8SJWuQYy/yiQy6or8dW6I7+B48S0ZxP0CkZ+oFJpkKKKYRixJNFVW4yonK8WW5MNC5hDZx6mCHdWMchYVOcqwk1Q2ga7S8eSdsuAsT2m0VmBSoNpNICcFPmt4dII3ykYTaVR9HWCkcLyTuMnRH8v5IfTRQIxoKS+WuaezmJHkwOj9KIy/uG0ED21nzQ4NL0rx/1VpJPOmRFmcCJPvb1PdS+z2VPWiaSAqFLPzRshOzFSV9OfqyXxT0fowcDxqu5iR9cfXvujMWnmvUjA/7Cil9k157/fwiE2kUXDSXarzFU2jNG0IeHpEd3GpcII3mD3i5BVKAD7qUoxFaIzq+S4R4JEZMUFpsDv65O+BO9drlI="
    # APPVEYOR_TOKEN
    - secure: "WG8FVhmErK4sbqYMQLMoKvI4Q+/Huq2TA96YjQOjmSoqZ6JbmVAGcQZKoHYgDpuquFPETzwZdTy1ffRUrfDflQ+u8HaFuJh78a9lJVh5jW8cQx/n6m+UpY6SW+EN3Z/8TtT5dYY14g/R1AntAGjhM6E6mtABVDS0wwuW0JahIGCB4QK7YgtGg8ulWZlgXCo5MF4WXQWalVMMnEYbAuGLleXjjRxnXP4I70Sg1oFOH4zDtUpBuS5ihdpuWed8BrQtlP7fz1DSo71BEfbxUN1wlKvm2sMEa/FRjGbeAiWs6WqmZdrXGFpJPL10Ss6BtDKxTcbOfn27IynkI/Dyw6v5Q8HIzLcWnIysJrsCHlMqoSI4X6Ooj+l0FWeCndZX5uq2iQS7v4n+cbn94fTgD69bsKLHWORnrmuK2CDpCGtdnFqAe2KX7EaUyJCq0l7SPZA698Xf0JiG+vdXCoVL4/wWPlv1/pE1HXb9HB3JpjpLshg1ENVWq/ksZ6Hi3rFLNlvXkxy/36cGjlDBx7CIlpCeVjhqi4+G3JgJvhQ/kaimglMkA33Yo8bxQoVo8nQKEJ79KPKLvATVHkmVRXBAvIFQ6AqLhYHFlTZF1/XQ7SblE0PCyLNs6s8yq25lOns6EfEhGl6wLyNBLXT33CAY/6eJRlsuHVfKT0yBAYhhQ0dltMM="
  matrix:
    include:
      - VSCODE_VERSION: "latest"
      - VSCODE_VERSION: "1.31.0"
      - VSCODE_VERSION: "insiders"
    allow_failures:
      - env: VSCODE_VERSION="insiders"

language: node_js

node_js: "10"

os:
  - linux
  - osx

before_install:
  - |
    if [ $TRAVIS_OS_NAME == "linux" ]; then
      export CXX="g++-4.9" CC="gcc-4.9"
      export DISPLAY=':99.0'
      /usr/bin/Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
      sleep 3
    fi

install:
  - npm install
  - npm audit || npm audit
  - npm run compile

script: 
  - npm test

after_failure:
  - cat ./out/tmp/workspaceFolder/FailedTestLogs/log_*.txt

jobs:
  include:
    - stage: deploy
      script: npm run deploy
      # https://docs.travis-ci.com/user/conditions-v1
      if: branch = master && type = push && tag IS blank && repo = matepek/vscode-catch2-test-adapter

