env:
  global:
    - C2_DEBUG=true
    # VSCE_PAT
    - secure: 'UvWVj7QFLCbqBXO6jLLQwWylMAaUHZfIyM/8p9fTrfvSHrfeHQ0UrYyvms8t7W3bPFcVA8Pf8DaOnACGT/SuS7m2Djlyc45frZeGk1j0MWhF7M+0SZeIMiELPQVlyL8uH5x5NqhFlBP6HvV341fImGm3t46SRgZFzU4TRYfgOA9I82BGY8/gr2rzniMos9fpNuxbyu30+PWDaGHL6Wvm0t91YrtWP0RQ9/sHKVkJDzlCejlk5aQe6EBuUuxz/dbSjEVNhzhHIYwhJEJ1/EAx+Ngz1QQIppwmwceql6dWHc9h+RUJAsFD/Q/xVwdT7gdUcWNty2QjqEsKc122Ll0opi+Za7NXj1m1Dn65Zayp7YY2WI6QmqRyFDHi7YF8naXj/HAwyB4B8VJYldErzsE5LQ0lBgUEtQhRwiQw1pr9nY6WRb7iw9TtK1yz79I3hk/+U7uFLixZ/HF7mCvaStB18VWODbxTnDPvq37Eooy6+Z3EGdyVDvjtEMPW7zdi589dKaEjG/KpQNqNAHuao/FEmx8pcngKSyGGchfiarzFaF8SSUubWk+WZXjwzjVVP5Adeq6pPp5ksFM7naSrsVolgtJ7OIJ+sqSMkaGySLLhdSREPB/K2WCBoznwj93eTIn6zGeKhKFLNMl14CGKaWd3G53YNykXf5x+eS1cQwGI+4o='
    # GITHUB_API_KEY
    - secure: 'EKVdnikYRiL/f07epf3IPinU9ckWXHXxQrkam23ZviPf/L5brYu+BPOm4oWLjv8ekwDIDan7A+y4Nzck7h5JDXxLcHcbsZIU6Fgo3pNULBNFI22VNo3NpL5CKVGJ8dMpTyvMztLvpFpBwGpszRTLmN6BrW/C/if7qfEOqqT9CVKk226Q2N+GP7w/vTzSZYkkf+C0dyTyV+j20ZkWgSxKMv57LlW5bNoMfQ1lOagna98Jl3NupynR9+qk4t4o67fYAB+5PEE9erICmwcPuhrJ0za61G1S4tPkoLu7lwV+pvOA6LUlkbwCcC7EofJx6w/S1VcK+Ebs3zNTcDZtGGG8DaEFvov4r+cpRGuAlQxb14aL6v3kv8edYGvtQOaSlkw7tktCz1/m6NiKIyxluf+RYVyPws944z4WanpCKbH4z7wTA7EbXDMfRDG643hv05KeamueouqUfdWpiKPm7d1vA4grH0Bl538xQ3PAdxDFd4TJ0eGxaz74BMTzHCmHutdatbCJnwgSEGnDNDKwM6lCUHi76pjAy4lfClG+0Y2TxErK/0pXK2kPmeP0FHAGkkHgSffG99cn8ulzvtJ8dmRKvk2ne/NzEsWgKq9aadHAyy/iMWr3yncbbBm+xo22jaN8M2ZWf9x0Mqc0uDc6iqVLKGqVXt6KJu8jL25B9Bc1xck='
    # APPVEYOR_TOKEN
    - secure: 'WG8FVhmErK4sbqYMQLMoKvI4Q+/Huq2TA96YjQOjmSoqZ6JbmVAGcQZKoHYgDpuquFPETzwZdTy1ffRUrfDflQ+u8HaFuJh78a9lJVh5jW8cQx/n6m+UpY6SW+EN3Z/8TtT5dYY14g/R1AntAGjhM6E6mtABVDS0wwuW0JahIGCB4QK7YgtGg8ulWZlgXCo5MF4WXQWalVMMnEYbAuGLleXjjRxnXP4I70Sg1oFOH4zDtUpBuS5ihdpuWed8BrQtlP7fz1DSo71BEfbxUN1wlKvm2sMEa/FRjGbeAiWs6WqmZdrXGFpJPL10Ss6BtDKxTcbOfn27IynkI/Dyw6v5Q8HIzLcWnIysJrsCHlMqoSI4X6Ooj+l0FWeCndZX5uq2iQS7v4n+cbn94fTgD69bsKLHWORnrmuK2CDpCGtdnFqAe2KX7EaUyJCq0l7SPZA698Xf0JiG+vdXCoVL4/wWPlv1/pE1HXb9HB3JpjpLshg1ENVWq/ksZ6Hi3rFLNlvXkxy/36cGjlDBx7CIlpCeVjhqi4+G3JgJvhQ/kaimglMkA33Yo8bxQoVo8nQKEJ79KPKLvATVHkmVRXBAvIFQ6AqLhYHFlTZF1/XQ7SblE0PCyLNs6s8yq25lOns6EfEhGl6wLyNBLXT33CAY/6eJRlsuHVfKT0yBAYhhQ0dltMM='
    # DEPLOYER_MAIL
    - secure: 'MtSVNng2I8yGJSUjXwSq+AJu8BeccladOT/QRS2lXEnJ66Fk22H0vTZCwmSB+4vVx9pt8ybBLqueNkcpcCZ1VxNWyYlWVFYt/jFbXKAcZpry0vYXKVHvf3Mofb/c/PBI7wl6CNFpMzGgDES9D+nbZCWUpzwnO47wLNmC2zKpE0eAQkdOIEHe7I4J5bfgE2i4VeRjzh2V7ZduMGUVnH/WEv51eQF4JLa/n0SWFn3SF1YQ/BOnLDcSyrofbadtoEHQ6OPYfHNRtOLUC07S1HOgAqFiAW+iZ4xP4345sBLF5ZldAEASWJMop4hH3TVG3cBxzuv6ubIgzKrsvj4KnytscBGZYcRP+JiLdY8Kf2qeJhApFrOKvBAt+GSeJygXHSC08Zm3vqDlFqUQpoNfAuBiCOd4uqZbCZewAt+ckQCl+QUOVHiJDgulPaDgQfgwcpIF/C9BqsS6d0CIYTq8rTObOYcT8qp+oJIoDRgnOfxelDl12RNFeqyyxY3orhPPk72B5/793F0YUwooJX+JfsN1aFdG1BE36k8fDijhR2P6g4YbIVGswyz6ugvUGC4PdPBr+1AIWCAYnUXGwS9CtIo7Y2dKuR2+Vz3CmT5A/HZsd9xXJoPibEMLYuSpbd+J5522/uMO+t0hjt7NGkZmzTHiElw6kUUS2Dt9vhBwpHmqCDo='
    # OVSX_PAT
    - secure: 'CdiXOyVkkhMcvxf0ob/m4UWqr+aG9WEYyxBPlLeR8rCn8O0BGdnyDwHVmXHOfYNOFtfqYT7XVqRw8rdbJCllS8GPe/qh4MySbcDheTKpe7sjdulW4IovVMDuMsSCtoDxPnOBhxHJ2gXYlZyISvg6g8uZqfxaNbAVoH9+5F5kEO3vd03KqHSNwvLepItikE9ECfIeAn+LN4yHB2FF0IYMSNn6rpTopcurPiSwk9BUZM++ELf6PS9s4jCHbVNA1AJ+4OrLy33/DCH+AdsXReK3Qh27ISoMBidaMVGt+fmX6j9FLnY31PX8WNUsQ9S3nO5BI/mDuQTW0hlJfLWQJsQ3x/zXhnrF9BuCKIXa+hKDjO8YVdiQbYfi7eTFzwDwwvoxzrpMZdsyjx2EeHxm7q7AFlOg4sgnd/tPdG9FRZLRwF8NmobpmIQIGoQIxwsmnMGHC1Anetcv57K0Jjmmhznm4w1C332Ia/clzyFWMkzuPqfViAkJudSaokWBeZjwBykFkomZB/jNhMNur4MQlSiyDcwbNWtquez8+tFURVBbP/NVeNLlfBLXm++OlPO2iouVJJuxCLbZ8jJKmzX7TtG82qFkGDtCSZNlq56zfbZPNzna39fhLxDFU1+20BkOydtI9H6ZJgFlCTP7LXEzLzFUOJH4cTh7ZNWgob3Go4qnBgU='

language: node_js

compiler: clang

node_js: '10'

before_install:
  - |
    if [ $TRAVIS_OS_NAME == "linux" ]; then
      #export CXX="g++-4.9" CC="gcc-4.9"
      export DISPLAY=':99.0'
      /usr/bin/Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
      sleep 3
    fi

install:
  - npm install
  - npm audit --production
  - npm run compile
  - npm run webpack # test dos not use it, but we are testing the webpack creation
  - ls -all out/dist

script:
  - npm test

# branches:
#   only:
#     - master

jobs:
  include:
    #- os: linux
    #  env: VSCODE_VERSION=latest
    - os: osx
      env: VSCODE_VERSION=latest

    #- os: linux
    #  env: VSCODE_VERSION=1.41.1
    #  if: branch = master
    - os: osx
      env: VSCODE_VERSION=1.41.1
      if: branch = master

    #- os: linux
    #  env: VSCODE_VERSION=insiders
    #  if: branch != master
    - os: osx
      env: VSCODE_VERSION=insiders
      if: branch != master

    - os: osx
      env: VSCODE_VERSION=latest
      stage: deploy
      script: npm run deploy
      # https://docs.travis-ci.com/user/conditions-v1
      if: branch = master && type = push && tag IS blank && repo = matepek/vscode-catch2-test-adapter

  allow_failures:
    - os: linux
      env: VSCODE_VERSION=insiders
    - os: osx
      env: VSCODE_VERSION=insiders
