sudo: false

env:
  global:
    - secure: "wbBkk3ujOixgrplG1baLP6lgjFr6bw2eiOsNYAyfwU8SeSoc4qgp8bGttigHOTwnPfAreLMlnGkFdPF3f8v31AHj98mevHKNxvkeFiRjDc9bI3rEviFnbZMWbsw7svzTw3/D4K1xZuHc46IReOU8OJUaQaAP/VquZ8S0ZLDyUslBLZyhQNgVtp5VmOyHie/iI+KvkOVZfhun2wVa5LJgmJJPCFIcPGdlWTf77InxZohBM1rPBB16UE/gXkLUlrMjqnZWRem92cN+mqkU7xolzeeWKdzvbD6pD0swCS3xbiFfwy9pHgxfDDYdqbQIuFKoRIOeIcSuFm8LQv5kXvdRGLM/aiND34V5rETB+uK9HCh66uDY/lpTVTpY8DlddbTitpgq1on1LEeVPdgvA1MU3wkQD++lrDT4hdNTNCsUvdbocceSlqEmrKycRUJCI8Z9HTnkCTXCITNFEw0brYTgrHE2+KY7ul4CYc0Xu0dHmm6SBHvdU38HLi4MRR/78VVP9anrH1zVVKiLP95vdFrwrXBFGewYVVwv4QjFuwnQFDTCLEYUNctyOF3H8pTLLbY0DWMM1LVU6abHfb0tDYpRCffKJv4Wf9wOcTNCemtaGaxgOY6vcy1/SmpVHa9WQkfDMywZrolByEwflw0wP/yUVdDVfRt/JeAVh9m4EhiHTc4="
    - secure: "KwwThYC5XnQXlt0r3mUfV91N9+4CujoCzrfb9eBhvfTQL0yRofx75saXWhh/HNC8fYsf/3cPV3iASKlUXCw2MjYw7w7pzmbeeszBRkMJQHdDFqaTmDY167vv88Mddd90quanM8EEdCpjvrLLzgGpxQGQzVRZ7z0SmxJIEF/I58aAmC8hZ++5V/zAlwnhCbvs8ppJB7zTf3Ug4rSVr1/q52CK5f0ZVwX1TqOlzHv7KFO7IZV5DWmYHsClvcJbraAtBUa0otNTzr6dIHq8K22MWBULHCvp2JziZ06F3jjfPk7yB0K8Ia8gy73n+rXyW8aikBpCCdhmAjHOOpB5VBM5I2/O1XYJY0rS4v6OoYUcw9rnbGY4tYh/k0We0cKgatbz43k6gYqO9bkjZMqZk/jqieQ8JKwfRQxd2SEd6tViuIzB1p3KqNDcG+0xAjgAMBy6LR8RSDbZJcPJ8Jv1WIB3xxL3m8REzIW3Fm1/hlJ+J1WzebK6D7Ypf0BOrRIU/XObDlpoFf2qdI9RgC/U4EULwUmGqEMd8W3moeU49QHx9MzIz4CEo03OODlP+dgDLmlVsjgP8+/ONUGJC/uqd8TvsNres5IS+/N8V2deLNxyyNvMV1DvbH1ogYnViM51Kn+Jq3bXqj39lYWYVkDk8SE9LR4/gmxwhmDQzuN+uwXi47o="
    
language: node_js

node_js:
  - "8"
  - "11"

os:
  - osx
  - linux

before_install:
  - if [ $TRAVIS_OS_NAME == "linux" ]; then
      export CXX="g++-4.9" CC="gcc-4.9" DISPLAY=:99.0;
      sh -e /etc/init.d/xvfb start;
      sleep 3;
    fi

install:
  - npm install
  - npm run compile

script: 
  - npm test --silent

before_deploy:
  - npm install 
  - npm run compile

deploy:
  provider: script
  script: bash src/repo_scripts/deploy.sh
  on:
    condition: "$TRAVIS_OS_NAME = osx"
    node_js: "8"
    repo: matepek/vscode-catch2-test-adapter
    branch: master
    tags: false
