environment:
  matrix:
    - nodejs_version: "8"
      platform: x86
      platform: x64
    - nodejs_version: "11"
      platform: x64      

install:
  - ps: Install-Product node $env:nodejs_version
  - node --version
  - npm --version
  - npm install

test_script:
  - npm run compile
  - npm test --silent

# Don't actually build.
build: off
