image:
  - Visual Studio 2017

platform:
  - x86
  - x64

environment:
  matrix:
    - nodejs_version: LTS
    - nodejs_version: Current
    - C2AVCVA: C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvarsall.bat

install:
  - ps: Install-Product node $env:nodejs_version
  - node --version
  - npm --version
  - npm install

build: off

test_script:
  - npm run compile
  - npm test --silent
