image:
  - Visual Studio 2017

platform:
  - x86
  - x64

environment:
  matrix:
    - nodejs_version: LTS
    - nodejs_version: Current

install:
  - ps: Install-Product node $env:nodejs_version
  - node --version
  - npm --version
  - npm install

build: off

test_script:
  - npm run compile
  - npm test --silent
