platform:
  - x86
  - x64

environment:
  matrix:
    - nodejs_version: "8"
    - nodejs_version: "11"

matrix:
  allow_failures:
    - platform: x86
      nodejs_version: "11"

install:
  - ps: Install-Product node $env:nodejs_version
  - node --version
  - npm --version
  - npm install

test_script:
  - npm run compile
  - npm test --silent

# Don't actually build.
build: off
