# https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions
name: Publish

on: push

jobs:
  build-linux:
    name: Build for Linux
    runs-on: ubuntu-latest
    #if: "contains(github.event.head_commit.message, '#ci') || startsWith(github.ref, 'refs/tags/')"

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: install
        run: |
          npm install
          npm audit --production

      - name: build
        run: |
          npm run compile
          npm run webpack # test does not use it, but we are testing the webpack creation
          ls -all out/dist
