name: Release-Legacy

on:
  # TODO: fix this
  # workflow_run:
  #   workflows: ['Test-Legacy']
  #   branches: [legacy]
  #   types: [completed]
  push:
    branches: [legacy] # TODO: this is the workaround

jobs:
  deploy:
    name: Conditionally Release and Deploy # depends on the content of CHANGELOG.md
    runs-on: ubuntu-latest
    environment: Release
    # TODO if: github.event.workflow_run.conclusion == 'success' && github.ref == 'refs/heads/legacy' && github.repository_owner == 'matepek'
    if: github.ref == 'refs/heads/legacy' && github.repository_owner == 'matepek'

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          persist-credentials: false # to drop github token and used GITHUBM_API_KEY

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'

      - name: Install
        run: npm install

      - name: Audit
        run: npm audit --production

      - name: Compile
        run: npm run compile

      - name: Deploy
        run: npm run deploy
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}
          GITHUBM_API_KEY: ${{ secrets.GITHUBM_API_KEY }}
